daqifi/daqifi-desktop

Daqifi.Desktop.Common/Loggers/AppLogger.cs
Daqifi.Desktop.DataModel/Channel/AdcMode.cs
Daqifi.Desktop.Test/Device/AbstractStreamingDeviceTests.cs
Daqifi.Desktop.Test/Exporter/LoggingSessionExporterTests.cs
Daqifi.Desktop/ConnectionManager.cs
Daqifi.Desktop/Device/DeviceMessage.cs
Daqifi.Desktop/Device/HidDevice/HidDeviceFinder.cs
Daqifi.Desktop/Device/IStreamingDevice.cs
Daqifi.Desktop/Device/SerialDevice/SerialDeviceFinder.cs
Daqifi.Desktop/Device/SerialDevice/UsbDevice.cs
Daqifi.Desktop/Device/WiFiDevice/DaqifiStreamingDevice.cs
Daqifi.Desktop/Loggers/DatabaseLogger.cs
Daqifi.Desktop/Loggers/LoggingManager.cs
Daqifi.Desktop/Loggers/PlotLogger.cs
Daqifi.Desktop/Loggers/SummaryLogger.cs
Daqifi.Desktop/MainWindow.xaml.cs
Daqifi.Desktop/ViewModels/DaqifiViewModel.cs

fixing some easy static code analysis issues

codacy cleanup

---

Daqifi.Desktop/Device/AbstractStreamingDevice.cs

Also handle getting data out of order (fake rollover)

Use the actual device timestamps.

---

Daqifi.Desktop.Setup/DAQifiDesktopSetup/Product.wxs
Daqifi.Desktop/Device/AbstractStreamingDevice.cs
Daqifi.Desktop/Device/IStreamingDevice.cs
Daqifi.Desktop/View/Flyouts/DevicesFlyout.xaml

- only show the range supported by Nq1
- added the part number to the display

fix: only show the analog input range supported by Nq1

---

Daqifi.Desktop.Common/Loggers/AppLogger.cs
Daqifi.Desktop/Properties/AssemblyInfo.cs

chore: let bugsnag know the version

---

Daqifi.Desktop.DataModel/Network/WifiSecurityType.cs

Added a couple of new wifi security types
closes #21

feat: updated wifi security types

---

CONTRIBUTING.md
README.md

Helpful for contributors outside the DAQiFi core team

docs: added a contribution guide

---

.github/workflows/prebuild.yaml

deps: updated to a newer version

---

Daqifi.Desktop.IO.Test/Messages/Producers/ScipMessageProducerTests.cs
Daqifi.Desktop/Device/WiFiDevice/DaqifiDeviceFinder.cs

Fixed device finder as it wasn't working, even though that code hasn't been touched in 7 years. Also fixed a test.

fix: fixed the device discovery

---

.github/workflows/build.yaml
Daqifi.Desktop.Common.Test/Daqifi.Desktop.Common.Test.csproj
Daqifi.Desktop.DataModel.Test/Daqifi.Desktop.DataModel.Test.csproj
Daqifi.Desktop.Test/Daqifi.Desktop.Test.csproj

chore: testing ci builds

---

.vscode/settings.json
Daqifi.Desktop.Bootloader.Test/Daqifi.Desktop.Bootloader.Test.csproj
Daqifi.Desktop.Bootloader.Test/FirmwareDownloaderTest.cs
Daqifi.Desktop.Bootloader/FirmwareDownloader.cs
Daqifi.Desktop/Daqifi.Desktop.csproj
Daqifi.Desktop/View/Flyouts/DevicesFlyout.xaml
Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
NuGet.config

- Added back uploading a hex firmware file. Note this only updates the firmware, not the WiFi firmware.
- Used Cursor to make a test for `FirmwareDownloader`
- Used Cursor to make a few other improvements
closes #101

feat: added back manual firmware update

---

Daqifi.Desktop.Test/Configuration/FirewallConfigurationTests.cs
Daqifi.Desktop.Test/Daqifi.Desktop.Test.csproj
Daqifi.Desktop/Configuration/FirewallManager.cs
Daqifi.Desktop/Daqifi.Desktop.csproj
Daqifi.Desktop/ViewModels/DaqifiViewModel.cs

on startup, the app checks for proper firewall rules and creates them if they don't exist.
closes #103

feat: adds firewall rules

---

Daqifi.Desktop.Setup/DAQifiDesktopSetup/DAQifiDesktop_Setup.wixproj
Daqifi.Desktop.Setup/DAQifiDesktopSetup/Product.wxs

fix: updated menu name with correct capitalizaiton

---

Daqifi.Desktop/View/Flyouts/DevicesFlyout.xaml

Will add it back once the hardware supports it.
closes #113

chore: removed ADC range

---

Daqifi.Desktop/Device/AbstractStreamingDevice.cs
Daqifi.Desktop/Device/SerialDevice/SerialStreamingDevice.cs
Daqifi.Desktop/ViewModels/DaqifiViewModel.cs

We simply restart the board after the update and everything is good.
closes #98

fix: Fixed device being in an unknown state after firmware/wifi update

---

.gitignore
Daqifi.Desktop.Common/Loggers/AppLogger.cs
Daqifi.Desktop.Setup/global.json

chore: Update .gitignore and remove client notifications from AppLogger

---

Daqifi.Desktop.Common/Loggers/AppLogger.cs
Daqifi.Desktop.Common/Loggers/NoOpLogger.cs

- Introduced test mode detection mechanism
- Created NoOpLogger for suppressing logs during testing
- Modified AppLogger to conditionally log or use NoOpLogger
- Added null checks and fallback for version retrieval
closes #121

chore: Add test mode support to AppLogger with NoOpLogger

---

Daqifi.Desktop/MainWindow.xaml
Daqifi.Desktop/View/ConnectionDialog.xaml

chore: swap MAC address for serial number

---

Daqifi.Desktop.Bootloader/Exceptions/FirmwareUpdateException.cs
Daqifi.Desktop.Bootloader/IFirmwareUpdateDevice.cs
Daqifi.Desktop.Bootloader/WiFiDownloader.cs
Daqifi.Desktop.Bootloader/WifiFirmwareDownloader.cs
Daqifi.Desktop.Bootloader/WifiModuleUpdater.cs
Daqifi.Desktop.IO/Messages/Producers/MessageProducer.cs
Daqifi.Desktop/ConnectionManager.cs
Daqifi.Desktop/Device/SerialDevice/SerialStreamingDevice.cs
Daqifi.Desktop/ViewModels/DaqifiViewModel.cs

Fixed an issue with firmware not updating. Also fine tuned the the firmware update progress bar.

fix: firmware not updating

---

.github/workflows/release.yaml

feat: add GitHub Actions workflow for automated release process

---

.github/workflows/build.yaml
.gitignore
Daqifi.Desktop.Bootloader.Test/Daqifi.Desktop.Bootloader.Test.csproj
Daqifi.Desktop.Common.Test/Daqifi.Desktop.Common.Test.csproj
Daqifi.Desktop.DataModel.Test/Daqifi.Desktop.DataModel.Test.csproj
Daqifi.Desktop.IO.Test/Daqifi.Desktop.IO.Test.csproj
Daqifi.Desktop.Test/Configuration/FirewallConfigurationTests.cs
Daqifi.Desktop.Test/Daqifi.Desktop.Test.csproj
Daqifi.Desktop/Configuration/FirewallManager.cs
Daqifi.Desktop/Services/AdminChecker.cs
Daqifi.Desktop/Services/MessageBoxService.cs

chore: add code coverage

---

.github/dependabot.yml

configuration for nuget and github-actions to weekly schedule with labels

chore: update dependabot 

---

.github/workflows/claude.yml

Enhancement
___
- Add Claude AI assistant GitHub Actions workflow
- Configure multiple trigger events for Claude integration
- Set up permissions and authentication for repository access
- Include optional configuration parameters for customization
___
```mermaid
flowchart LR
A["GitHub Events"] --> B["Claude Workflow Trigger"]
B --> C["Checkout Repository"]
C --> D["Run Claude Code Action"]
D --> E["AI Assistant Response"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>claude.yml</strong><dd><code>Add Claude AI GitHub Actions workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

"Claude PR Assistant workflow"
